### ISSUE TITLE
"Unable to Locate Library (while searching for a .vos file.)"

### ISSUE THREAD

**Issue by juliangould** [coq-community/vscoq#244] opened 2021-06-25 17:32 UTC
Background:

- 2015 MacBook running OSX Big Sur v11.4
- Coq 8.13.2
- VSCoq 0.3.5

Issue:

I'm having trouble with the "Require Import" command for a compiled .v file. Even when I have the files in the same directory, I'm getting the following error message:

"Unable to locate library ______ (While searching for a .vos file.)"

where ______ is name of the file. 

As a trivial example, consider the following example (attached .zip folder).
[coqTest.zip](https://github.com/coq-community/vscoq/files/6717906/coqTest.zip)

- a.v is an empty file (compiled)
- b.v simply contains the line "Require Import a."

when I try to compile b.v or even step through line by line, I get the error message above.

Any help would be appreciated! Thanks!

**Comment by paigenorth** [comment] 2021-06-27 17:29
I have tried to help @juliangould but could not find the root of the problem. I cannot reproduce the problem, even though I have a very similar set-up: macOS 11.3, Coq 8.13.2, VSCode 1.57.1, VSCode 0.3.5.

Any help would be greatly appreciated!

**Comment by fakusb** [comment] 2021-06-28 10:17
I the folder that is "open" is vscoq (File -> open folder) the one that (directly) contains the two files?

**Comment by juliangould** [comment] 2021-06-28 16:32
Hey Fabian,

Thank you for looking into this! Could I have a little more detail on your
question? I'm not sure I understand it. Thanks!


Best,
Julian

**Comment by fakusb** [comment] 2021-07-02 08:07
In vscode, you do not only open files, but also have a "workspace", which usually is a folder in which the "project" is contained: https://code.visualstudio.com/docs/editor/workspaces

I was wondering whether your workspace is the folder that contains the relevant files. You cna make sure it is by opening the folder manually, as i described.

**Comment by mukeshtiwari** [comment] 2021-08-04 01:55
> I have tried to help @juliangould but could not find the root of the problem. I cannot reproduce the problem, even though I have a very similar set-up: macOS 11.3, Coq 8.13.2, VSCode 1.57.1, VSCode 0.3.5.
> 
> Any help would be greatly appreciated!

That's very interesting.  I am facing the same problem as @juliangould. Below is the content of directory and  when I am trying to open Maring.v in VS Code, I am getting this error: Unable to locate library ListLemma. (While searching for a .vos file.) coqtop. However, if I open the file in Emacs, it's working fine. 

```
(base) ➜  Schulze_Crypto_Verification git:(main) ls
LICENSE                ListLemma.vo           Margin.glob            Margin.vok             README.md              Schulze_Plaintext.vo   Schulze_Plaintext.v~   ValidityExist.vo
ListLemma.glob         ListLemma.vok          Margin.v               Margin.vos             Schulze_Plaintext.glob Schulze_Plaintext.vok  ValidityExist.glob     ValidityExist.vok
ListLemma.v            ListLemma.vos          Margin.vo              Margin.v~              Schulze_Plaintext.v    Schulze_Plaintext.vos  ValidityExist.v        ValidityExist.vos
(base) ➜  Schulze_Crypto_Verification git:(main) which coqtop
/Users/mukesht/.opam/default/bin/coqtop
(base) ➜  Schulze_Crypto_Verification git:(main) coqtop --version
The Coq Proof Assistant, version 8.12.2 (January 2021)
compiled on Jan 13 2021 6:33:26 with OCaml 4.09.1
```
VS Code Screen Shot
![Screen Shot 2021-08-04 at 11 47 14 am](https://user-images.githubusercontent.com/1135077/128108860-4899c64c-4455-4a6f-b117-4cc4a6db2528.png)

Emacs Buffer Screen Shot
![Screen Shot 2021-08-04 at 11 50 06 am](https://user-images.githubusercontent.com/1135077/128109065-be77615d-5d64-491d-9b6c-585133807f22.png)


My VS Code 
version: 1.58.2
Commit: c3f126316369cd610563c75b1b1725e0679adfb3
Date: 2021-07-14T22:09:06.581Z (2 wks ago)
Electron: 12.0.13
Chrome: 89.0.4389.128
Node.js: 14.16.0
V8: 8.9.255.25-electron.0
OS: Darwin x64 20.6.0

My OS:
macOS Big Sur (version 11.5.1)

**Comment by fakusb** [comment] 2021-08-04 08:51
Great that it works now, i'll close this unless there is another problem.

**Closed by fakusb** 2021-08-04 08:51 UTC
