### ISSUE TITLE
bodies of context variables should be visible by default

### ISSUE THREAD

**Issue by JasonGross** [coq-community/vscoq#596] opened 2023-08-24 22:54 UTC
![image](https://github.com/coq-community/vscoq/assets/396076/d3ab0005-1e8f-4c41-9d47-29191dfd1122)

**Comment by maximedenes** [comment] 2023-08-26 12:46
Oh! This is definitely not the intended behavior. Thanks for reporting!

**Comment by gares** [comment] 2023-08-26 13:54
At the same time it is where some folding can help, esp for Let from a section.

**Comment by maximedenes** [comment] 2023-08-28 11:51
@JasonGross In fact, this is already fixed in 1.9.3 (probably a by-product of #559 or #593). Would you mind trying out and reopening if still not working for you?

**Closed by maximedenes** 2023-08-28 11:51 UTC
