### ISSUE TITLE
[vscoq2] Syntax of mathcomp2 

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#661] opened 2023-10-11 15:09 UTC
vscoq does not seem to recognize HB syntax.
This problem was described in [zulip](
https://coq.zulipchat.com/#narrow/stream/237662-VsCoq-devs-.26-users/topic/vscoq2.20and.20mathcomp2)

```coq
From HB Require Import structures.
From mathcomp Require Import all_ssreflect.

Set Implicit Arguments.
Unset Strict Implicit.
Unset Printing Implicit Defensive.

Definition eq_axiom1 T (e : rel T) := forall x y, reflect (x = y) (e x y).

HB.mixin Record hasDecEq1 T := { eq_op : rel T; eqP : eq_axiom1 eq_op }.
```

**Comment by Blaisorblade** [comment] 2023-10-12 03:35
I'd assume this is a duplicate of https://github.com/coq-community/vscoq/issues/661 and then issues like https://github.com/LPCIC/coq-elpi/issues/516 . Tentatively closing as duplicate.

**Closed by Blaisorblade** 2023-10-12 03:35 UTC
