### ISSUE TITLE
Debug output is printed reverse

### ISSUE THREAD

**Issue by thomas-lamiaux** [coq-community/vscoq#873] opened 2024-08-24 16:08 UTC
Hi, I was trying debug auto with VsCoq2 and it seems that messages are printed in the reverse order. The following returns

```Coq
Goal forall {P Q R}, (P -> Q) -> R -> P -> Q.
  intros. debug auto.

** assumption. (*success*)
* simple apply X. (*success*)
* intro. (*fail*)
* assumption. (*fail*)
(* debug auto: *)
```
which seems reversed to me

**Comment by thomas-lamiaux** [comment] 2024-08-25 00:44
Actually, is linked to sequential printing
```
Goal 0 = 0.
  idtac "1"; idtac "2".
  
2
1
```

**Comment by rtetley** [comment] 2024-08-26 07:53
Duplicate of #705. I'll keep open as their is a PR mentioning this one ! Thanks for reporting :-)

**Closed** 2024-08-26 08:26 UTC
