### ISSUE TITLE
Issues with Ltac2 (seen the same before in CoqIDE and PG).

### ISSUE THREAD

**Issue by MSoegtropIMC** [coq-community/vscoq#282] opened 2022-03-08 13:54 UTC
Dear VsCoq Team,

I have some issues with Ltac2. When I open the below code as file "Test.v":
```
Require Import Ltac2.Ltac2.

Ltac2 Notation "dbg" t(thunk(tactic(6))) := t ().
```
and step over it once, everything is fine. If I step 2x up over the Ltac2 require again and 2x down again it fails with error:
```
Syntax error: [input_fun] expected after [binder] (in [tac2def_body]).
Not in proof mode.
```
There was a similar issue in CoqIDE that one cannot step back and forth over the Ltac2 require, but this was fixed a while back (see https://github.com/coq/coq/issues/11793).

I am using vsCoq 0.3.6 and Coq 8.15.0 (from Coq Platform).

Btw.: It is not so super clear to me which coq is used - VsCoq appears to use what was selected in opam when VsCoq was started - some version info when coqtop starts would be nice.

**Comment by SkySkimmer** [comment] 2022-03-08 14:21
>There was a similar issue in CoqIDE that one cannot step back and forth over the Ltac2 require, but this was fixed a while back (see coq/coq#11793).

That looks closed as duplicate of something still open (https://github.com/coq/coq/issues/12575) not fixed

**Comment by MSoegtropIMC** [comment] 2022-03-08 15:56
Well but it is fixed in CoqIDE in 8.15.

**Comment by SkySkimmer** [comment] 2023-01-03 16:32
I think this is fixed in Coq master but I don't have vscode installed so didn't test. See https://github.com/coq/coq/issues/11793#issuecomment-1369973774

**Comment by rtetley** [comment] 2023-09-04 07:52
Closing this issue as it seems fixed in VsCoq 2

**Closed by rtetley** 2023-09-04 07:52 UTC
