### ISSUE TITLE
Processing continues after a failed Require Import

### ISSUE THREAD

**Issue by tchajed** [coq-community/vscoq#917] opened 2024-09-27 12:08 UTC
If you process any file with a Require Import that fails (eg, because the dependency isn't compiled), VsCoq proceeds over the Require Import and reports an error, but then _continues going_. This is very confusing because the rest of the file isn't going to work.

Software Foundations' Induction chapter (without running `make`) is a simple test case.

**Comment by rtetley** [comment] 2024-10-02 09:07
I believe this is a duplicate of #877

**Closed** 2024-10-02 09:51 UTC
Labels: bug
