### ISSUE TITLE
Search crashes vscoqtop and extension doesn't recover

### ISSUE THREAD

**Issue by Dashadower** [coq-community/vscoq#655] opened 2023-10-10 12:49 UTC
I have the 2.0.1+coq8.18 version installed with OCaml 5.1.0 on Code 1.83.0

Frequently when performing a search from the query side panel, the search will fail with a `Error Connection got disposed.` message and disables the entire extension until I reload the window. I have added the `-bt, -vscoq-d, all` flags and have observed the following Language Server output on the error:

```
[lspManager          , 52586, 1696941448.227207] UI req ready
[top                 , 52586, 1696941448.227293] Main loop event ready: Request , 2 events waiting
[lspManager          , 52586, 1696941448.227298] ui request: vscoq/search
[top                 , 52586, 1696941448.227334] ==========================================================
[top                 , 52586, 1696941448.227454] Uncaught exception Not_found.
Raised at Stdlib__Hashtbl.find in file "hashtbl.ml", line 546, characters 17-32
Called from Dune__exe__LspManager.coqtopSearch in file "vscoqtop/lspManager.ml", line 392, characters 11-56
Called from Dune__exe__LspManager.handle_lsp_event in file "vscoqtop/lspManager.ml", line 476, characters 31-56
Called from Dune__exe__Vscoqtop.loop.loop in file "vscoqtop/vscoqtop.ml", line 28, characters 21-50
Called from Dune__exe__Vscoqtop.loop in file "vscoqtop/vscoqtop.ml", line 33, characters 6-15

[top                 , 52586, 1696941448.227459] ==========================================================
[Info  - 9:37:28 PM] Connection to server got closed. Server will restart.
...
```

Immediately after the error occurs when I run interpret through keyboard hotkeys the Language Server output does update showing the highlight and result, but not the proofview or the green highlighting in the editor itself which seems like the language server is restarted correctly but not the UI portions of the editor.

**Comment by Dashadower** [comment] 2023-10-15 05:11
> Do you think you could find a small example of a search that triggers the Not_found issue so that I could reproduce and fix ? Thanks for the feedback :-)

Hi, Thanks for the reply and the great extension. I'm going through a chapter in Logical Foundations of Software Foundations so it's quite hard to isolate an example, but the way I was able to consistently reproduce the error was through:

1. Reload the window so the server isn't running.
2. Interpret the first few lines that does the setup and imports. In the chapter I'm reading(`IndProp.v`), it would be just the following two lines:
    ```
    Set Warnings "-notation-overridden,-parsing,-deprecated-hint-without-locality".
    From LF Require Export Logic.
    ```
3. I would then search any term that wasn't interpreted yet, which wouldn't show any results(`"app_nil_r"` in my case). Trying to search again by pressing enter a couple more times in the search bar would crash the language server.

**Comment by mizlan** [comment] 2024-01-27 19:56
Search also crashes for me. For me, it is not just uninterpreted terms, it is any. It freezes my language server client in Neovim and causes VSCode extension to report to me a crash. Not sure how I can debug to get a stacktrace.

**Comment by rtetley** [comment] 2024-07-22 08:55
Unable to reproduce on master. Closing.

**Closed by rtetley** 2024-07-22 08:55 UTC
Labels: bug
