### ISSUE TITLE
Manual mode :  the cursor does not follow the green zone

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#516] opened 2023-07-12 15:28 UTC
with vscoq 2.0.0  and the manual mode, performing the `Step Forward` does not move the cursor anymore.
For compatibility, would be nice to have an option to get a sticky cursor.

**Comment by rtetley** [comment] 2023-07-20 06:55
Duplicate of #505

**Closed by rtetley** 2023-07-20 06:55 UTC
Labels: enhancement
