### ISSUE TITLE
[vscoq1] ProofMode horizontal scroll

### ISSUE THREAD

**Issue by andreiburdusa** [coq-community/vscoq#404] opened 2023-02-18 13:42 UTC
Often, when line lengths exceed the available width in ProofMode, they cause horizontal scroll instead of wrapping. I think this is not right because changing the size of the ProofMode window or of the entire editor window always wraps the lines.

**Comment by thery** [comment] 2023-02-18 15:30
which version of vscoq are you using? A screenshot of the problem would also be more than welcome.
Thanks

**Comment by andreiburdusa** [comment] 2023-02-18 17:02
I'm using VSCoq v0.3.7
This is how the problem looks like:
![Screenshot from 2023-02-18 18-56-48](https://user-images.githubusercontent.com/53746396/219878339-c5068451-4448-4990-847a-e427282e7819.png)
It goes away when I change the size of the window:
![Screenshot from 2023-02-18 18-57-01](https://user-images.githubusercontent.com/53746396/219878494-4a7b62ba-b579-477c-84f7-14c41063b2d7.png)

**Comment by 4ever2** [comment] 2023-02-18 18:59
This is because the printing width will get reset if a user steps backwards after resizing the ProofView.

**Comment by thery** [comment] 2023-02-18 19:06
and initially it is not set to a "reasonable" value.

**Comment by thery** [comment] 2023-02-18 19:10
maybe a fix for the initial problem would be to generate a dummy resizeEvent to get a reasonable "Printing Width"  but this will not fix @4ever2 undo problem

**Comment by 4ever2** [comment] 2023-02-18 19:19
I believe that #405 should fix this.

**Comment by 4ever2** [comment] 2023-02-18 19:30
> and initially it is not set to a "reasonable" value

The initial value isn't a problem. A resizeEvent get generated when the proofView is opened so a reasonable value is set. However, if the user steps back to before the first sentence then the printing width value will be set to the Coq default value (75 or 78 based on which Coq version is used).

**Comment by thery** [comment] 2023-02-18 22:38
@4ever2  ok #405 seems to fix the problem (at least I can't reproduce it anymore). Thanks.
@andreiburdusa could you try if it is ok for you too?  You can either pull #405 and type `make` to build  `vscoq-0.3.7.vsix` or just unzip this [vscoq-0.3.7.vsix.zip](https://github.com/coq-community/vscoq/files/10775318/vscoq-0.3.7.vsix.zip). Then you just need to do a  `code --install-extension vscoq-0.3.7.vsix` to test the new version.  Thanks!

**Comment by andreiburdusa** [comment] 2023-02-19 07:56
I tested the new version. The problem I had was fixed. Thank you for taking care so fast!

**Comment by thery** [comment] 2023-02-19 08:23
@andreiburdusa Thanks to you for reporting it! The fix has been merged to the [development branch]( https://github.com/coq-community/vscoq/tree/vscoq1) and will be available soon with `0.3.8`.

**Closed** 2023-02-19 09:14 UTC

**Comment by thery** [comment] 2023-03-01 13:49
@andreiburdusa 0.3.8 is out. It should fix your problem
