### ISSUE TITLE
Errors in query make vscoq crazy 

### ISSUE THREAD

**Issue by CohenCyril** [coq-community/vscoq#13] opened 2019-07-17 16:27 UTC

**Comment by maximedenes** [comment] 2019-07-19 11:22
@gares when I send a `Query` to coq, I get a "processed" feedback. What is the point of this feedback? And it seems to carry routeId 0 whatever routeId I give to the query.

Other question: IIUC, successful results of queries are asynchronous, but errors are synchronous. What's the motivation for making them synchronous?

**Comment by gares** [comment] 2019-07-19 12:13
For the feedback I'm afraid it is just because we use the same codepath for regular commands, eg Reach.known_state. I guess it is fixable to use the right route. Best would be not to use the standard vernac interpretation code path for things that, like query, are not pieces of the document to be evaluated.

Wrt sync/async I think there is a misconception: it is not that "feedback means asynchronous".

Queries can be made async, but it is not the default (it was with async-proofs-full but we removed the option so I don't know if it can be enabled easily). By default they are synchronous, the fact that the output is a feedback rather than a Printf is, I guess, because all output has been progressively moved to that channel (indeed the original Query protocol message was carrying the synchronous output as a string).

What to concretely do in today's VScoq is unclear to me since I don't know how it works internally and this bugreport is not very informative. I guess we can chat on Monday to find a good angle.

**Comment by maximedenes** [comment] 2019-09-04 10:02
@CohenCyril I can't reproduce this in the current VsCoq `master`. Can you confirm that the problem is still present?

**Comment by maximedenes** [comment] 2019-09-09 17:43
@CohenCyril any news?

**Comment by CohenCyril** [comment] 2019-09-10 08:43
> @CohenCyril any news?

I did not get the chance to try yet...

**Comment by maximedenes** [comment] 2019-09-19 14:21
Could not reproduce so closing. Feel free to reopen with a reproducible test case.

**Closed by maximedenes** 2019-09-19 14:21 UTC
Labels: bug
