### ISSUE TITLE
[vscoq2] Language Server Crash on an intro evaluation.

### ISSUE THREAD

**Issue by noahkohrs** [coq-community/vscoq#637] opened 2023-09-26 09:02 UTC
### Here's the Proof that made the server down on the line "intro c0rou".

```coq
Theorem th_crou_gen : forall c : coulfeu, c = Rouge -> coul_suiv c = Vert.
Proof.
  intro c0.
  (** Pour démontrer [c0 = Rouge -> coul_suiv c0 = Vert],
      on suppose [c0 = Rouge]
      et on doit alors prouver [coul_suiv c0 = Vert]
      sous cette hypothèse supplémentaire ;
      lorsque l'on introduit une hypothèse, on lui donne un nom. *)
  intro c0rou. (* /!\   CRASH ON THIS LINE   /!\ *)
  (** Le raisonnement sous-jacent est :
      soit c0rou une preuve arbitraire (inconnue) de [c0 = Rouge],
      on peut s'en servir pour démontrer coul_suiv [c0 = Vert]. *)
  rewrite c0rou. cbn [coul_suiv]. reflexivity.
Qed.
```

### Note that it uses theses :

```coq
Inductive coulfeu : Set :=
  | Vert : coulfeu
  | Orange : coulfeu
  | Rouge : coulfeu
.


Definition coul_suiv : coulfeu -> coulfeu :=
  fun c =>
    match c with
    | Vert => Orange
    | Orange => Rouge
    | Rouge => Vert
    end.
```

**Comment by rtetley** [comment] 2023-09-28 11:48
I am unable to reproduce this crash. Could you give more information on your set up and maybe the error message for context ? You can get more information in the Coq Language Sever tab by editing Vscoq:Args in user settings. For reference add this: 
```json
"vscoq.args": [
        "-bt",
        "-vscoq-d", 
        "all",
    ],
```

**Comment by rtetley** [comment] 2024-08-26 09:10
Closing as I am unable to reproduce.

**Closed by rtetley** 2024-08-26 09:10 UTC
