### ISSUE TITLE
Stepping when an error occurs in manual mode

### ISSUE THREAD

**Issue by thery** [coq-community/vscoq#639] opened 2023-09-28 10:47 UTC
I find disturbing when I try to perform one step in manual mode that if there is an error it is trying to execute something that could be far away.

Here I've tried to execute the first line and the third line got executed

![ddd](https://github.com/coq-community/vscoq/assets/6795190/59560df0-464e-4a07-b55d-48b77fa82886)

Would it be possible to just refuse to execute anything if the line contains an error?

**Comment by rtetley** [comment] 2023-09-28 10:59
I believe this is a duplicate of #537

**Comment by thery** [comment] 2023-09-28 11:04
yes https://github.com/coq-community/vscoq/issues/537 seems more related to jump to point (stowhile here my problem is more with the one step . But maybe it can be solved by the same fix.

**Comment by rtetley** [comment] 2024-08-26 10:44
Closed by #537

**Closed by rtetley** 2024-08-26 10:44 UTC
Labels: duplicate
